<div id="header">
    <div id="logo">
        <div id="logo_text">
            <!-- class="logo_colour", allows you to change the colour of the text -->
            <h1><a href="#">simple<span class="logo_colour">style_blue_trees</span></a></h1>
        </div>
    </div>
    <div id="menubar">
        <ul id="menu">
            <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
            <li class="selected"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            <?php if($this->identity()): ?>
                <li>Hello <?php echo $this->identity()->name ?></li>
                <li><a href="<?php echo $this->url('logout') ?>">Logout</a></li>
            <?php else: ?>
            <li><a href="<?php echo $this->url('login') ?>">Login</a></li>
            <li><a href="<?php echo $this->url('register') ?>">Register</a></li>
            <?php endif; ?>

        </ul>
    </div>
</div>