<div id="header">
    <div id="logo">
        <div id="logo_text">
            <!-- class="logo_colour", allows you to change the colour of the text -->
            <h1><a href="#">simple<span class="logo_colour">style_blue_trees</span></a></h1>
        </div>
    </div>
    <div id="menubar">
        <ul id="menu">
            <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
            <li class="selected"><a href="#">Home</a></li>
            <li><a href="#">Examples</a></li>
            <li><a href="#">A Page</a></li>
            <li><a href="#">Another Page</a></li>
            <li><a href="#">Contact Us</a></li>
        </ul>
    </div>
</div>