<?php
$form = $this->form;
?>
<div id="content">
    <!-- insert the page content here -->
    <?php echo $this->form()->openTag($form); ?>
    <h1>User register</h1>
    <div>
        <label for="">Name</label>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>

    <br>

    <div>
        <label for="">Email</label>
        <?php echo $this->formInput($form->get('email')); ?>
    </div>

    <br>

    <div>
        <label for="">Password</label>
        <?php echo $this->formInput($form->get('password')); ?>
    </div>
    <a href="javascript:void(0)" onclick="App.submit('register-form')">Register</a>

    <p>
        <?php if(!empty($this->error)) echo $this->error;?>
        <?php echo $this->flashMessenger()->render();?>
    </p>
    <?php echo $this->form()->closeTag(); ?>

</div>