<?php
$categories = $this->data;
?>
<div id="sidebar_container">
    <div class="sidebar">
        <div class="sidebar_top"></div>
        <div class="sidebar_item">
            <h3>Post category</h3>
            <ul>
                <?php
                foreach($categories as $key => $item):
                ?>
                <li><a href="#"><?php echo str_repeat('-',$item['level']-1). ' '. $item['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="sidebar_base"></div>
    </div>
    <div class="sidebar">
        <div class="sidebar_top"></div>
        <div class="sidebar_item">
            <h3>Search</h3>
            <form method="post" action="#" id="search_form">
                <p>
                    <input class="search" type="text" name="search_field" value="Enter keywords....." />
                    <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="style/search.png" alt="Search" title="Search" />
                </p>
            </form>
        </div>
        <div class="sidebar_base"></div>
    </div>
</div>